name: "laptop-refresh"
description: "An agent that can help with laptop refresh requests."
instructions: in file in config/prompts directory
tool_choice: "required"
input_shields: []
output_shields: []
max_infer_iters: 25
enable_session_persistence: true
sampling_params:
  strategy:
    type: "top_p"
    temperature: 0.7
    top_p: 0.95
  max_tokens: 2000
mcp_servers: ["employee-info", "snow"]
knowledge_bases: ["laptop-refresh"]
