{{- if and .Values.slack.enabled .Values.slack.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "self-service-agent.fullname" . }}-slack
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: slack
spec:
  host: {{ .Values.slack.route.host }}
  to:
    kind: Service
    name: {{ include "self-service-agent.fullname" . }}-slack
    weight: 100
  port:
    targetPort: slack
  {{- if .Values.slack.route.tls.enabled }}
  tls:
    termination: {{ .Values.slack.route.tls.termination }}
  {{- end }}
{{- end }}
