replicaCount: 1

image:
  repository: quay.io/ecosystem-appeng/self-service-agent-slack-service
  pullPolicy: Always

# Image pull secrets
imagePullSecrets: []

# Name overrides
nameOverride: ""
fullnameOverride: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Pod security context
podSecurityContext: {}

# Container security context
securityContext: {}

# Service configuration
service:
  type: ClusterIP
  port: 8000

# Route configuration
route:
  enabled: true
  host: ""
  tls:
    enabled: true
    termination: edge

# Slack settings
slack:
  botToken: ""
  signingSecret: ""

resources: {}

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}