apiVersion: v1
kind: Service
metadata:
  name: {{ include "slack-service.fullname" .  }}
  labels: {{- include "slack-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "slack-service.selectorLabels" . | nindent 8 }}