name: Build and push images

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
 VERSION: ${{ github.head_ref || github.ref_name }}.${{ github.sha }}
 REGISTRY: quay.io/ecosystem-appeng

jobs:
  build-and-push:
    if: github.repository_owner == 'RHEcosystemAppEng'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build all Images
        run: make build-all-images
        
      - name: Push all Images
        run: make push-all-images
